name: Compile Windows Binary
description: Compile Windows binary and cache for integration tests

inputs:
  cache-key-suffix:
    description: Suffix for cache key
    required: true
  binary-cache-key:
    description: Cache key for binary
    required: true
  binary-path:
    description: Path where to build the binary
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v6

    - name: setup Go
      uses: magnetikonline/action-golang-cache@v5
      with:
        go-version-file: go.mod
        cache-key-suffix: ${{ inputs.cache-key-suffix }}

    - name: build Windows binary
      shell: bash
      run: |
        go generate ./...
        mkdir -p $(dirname ${{ inputs.binary-path }})
        CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags "-s -w" -o ${{ inputs.binary-path }}

    - name: cache binary
      uses: actions/cache/save@v4
      with:
        path: ${{ inputs.binary-path }}
        key: ${{ inputs.binary-cache-key }}-${{ github.sha }}
