name: Run Integration Test
description: Run E2E integration test

inputs:
  label:
    description: Test label to filter
    required: true
  needs-kind:
    description: Whether this test needs kind
    required: false
    default: "false"
  gh-username:
    description: GitHub username for private repo tests
    required: true
  gh-access-token:
    description: GitHub access token for private repo tests
    required: true
  binary-cache-key:
    description: Cache key for binary
    required: true
  binary-path:
    description: Path where the binary is located
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v6

    - name: restore cached binary
      id: cache-restore
      uses: actions/cache/restore@v4
      with:
        path: ${{ inputs.binary-path }}
        key: ${{ inputs.binary-cache-key }}
        enableCrossOsArchive: true

    - name: setup Go (if cache miss)
      if: steps.cache-restore.outputs.cache-hit != 'true'
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: rebuild binary (if cache miss)
      if: steps.cache-restore.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir -p $(dirname ${{ inputs.binary-path }})
        if [[ "${{ inputs.binary-path }}" == *"windows"* ]]; then
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags "-s -w" -o ${{ inputs.binary-path }}
        else
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o ${{ inputs.binary-path }}
        fi

    - name: make binary executable
      if: runner.os != 'Windows'
      shell: bash
      run: chmod +x ${{ inputs.binary-path }}

    - name: pre-pull docker images
      description: Pre-pull commonly used docker images to speed up tests
      shell: bash
      run: |
        docker pull alpine
        docker pull ubuntu
        docker pull mcr.microsoft.com/devcontainers/go:1
        docker pull mcr.microsoft.com/devcontainers/python:latest

    # NOTE: engineerd/setup-kind does not work on Windows runners
    - name: setup kind
      if: inputs.needs-kind == 'true' && runner.os != 'Windows'
      uses: engineerd/setup-kind@v0.6.2
      with:
        version: "v0.24.0"
        image: kindest/node:v1.34.0@sha256:7416a61b42b1662ca6ca89f02028ac133a309a2a30ba309614e8ec94d976dc5a
        name: ${{ inputs.label }}

    - name: run test (Linux)
      if: runner.os != 'Windows'
      shell: bash
      working-directory: ./e2e
      env:
        GH_USERNAME: ${{ inputs.gh-username }}
        GH_ACCESS_TOKEN: ${{ inputs.gh-access-token }}
      run: |
        sudo \
          GH_USERNAME="${GH_USERNAME}" \
          GH_ACCESS_TOKEN="${GH_ACCESS_TOKEN}" \
          KUBECONFIG="${KUBECONFIG:-$HOME/.kube/config}" \
          PATH="${PATH}" \
          GOROOT="${GOROOT}" \
          go test -v -ginkgo.v -timeout 3600s --ginkgo.label-filter=${{ inputs.label }}

    - name: run test (Windows)
      if: runner.os == 'Windows'
      shell: bash
      working-directory: ./e2e
      env:
        GH_USERNAME: ${{ inputs.gh-username }}
        GH_ACCESS_TOKEN: ${{ inputs.gh-access-token }}
      run: |
        GH_USERNAME="${GH_USERNAME}" \
          GH_ACCESS_TOKEN="${GH_ACCESS_TOKEN}" \
          KUBECONFIG="${KUBECONFIG:-$HOME/.kube/config}" \
          PATH="${PATH}" \
          GOROOT="${GOROOT}" \
          go test -v -ginkgo.v -timeout 3600s --ginkgo.label-filter=${{ inputs.label }}
