name: Run Integration Test
description: Run E2E integration test

inputs:
  label:
    description: Test label to filter
    required: true
  needs-kind:
    description: Whether this test needs kind
    required: false
    default: "false"
  gh-username:
    description: GitHub username for private repo tests
    required: true
  gh-access-token:
    description: GitHub access token for private repo tests
    required: true
  binary-cache-key:
    description: Cache key for binary
    required: true
  binary-path:
    description: Path where the binary is located
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v6

    - name: restore cached binary
      id: cache-restore
      uses: actions/cache/restore@v5
      with:
        path: ${{ inputs.binary-path }}
        key: ${{ inputs.binary-cache-key }}
        enableCrossOsArchive: true

    - name: setup Go (if cache miss)
      if: steps.cache-restore.outputs.cache-hit != 'true'
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: rebuild binary (if cache miss)
      if: steps.cache-restore.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir -p $(dirname ${{ inputs.binary-path }})
        if [[ "${{ inputs.binary-path }}" == *"windows"* ]]; then
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags "-s -w" -o ${{ inputs.binary-path }}
        else
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o ${{ inputs.binary-path }}
        fi

    - name: make binary executable
      if: runner.os != 'Windows'
      shell: bash
      run: chmod +x ${{ inputs.binary-path }}

    # NOTE: Pre-pull commonly used docker images to speed up tests
    # with retry logic to handle transient network issues. Limited to 'up'
    # tests to avoid unnecessary pulls.
    - name: pre-pull docker images
      if: inputs.label == 'up'
      shell: bash
      run: |
        pull_with_retry() {
          local image=$1
          local max_attempts=5
          local attempt=1
          local delay=3

          while [ $attempt -le $max_attempts ]; do
            echo "Pulling $image (attempt $attempt/$max_attempts)"
            if docker pull "$image"; then
              echo "Successfully pulled $image"
              return 0
            fi
            if [ $attempt -lt $max_attempts ]; then
              echo "Failed to pull $image, retrying in ${delay}s"
              sleep $delay
              delay=$((delay * 2))
            fi
            attempt=$((attempt + 1))
          done
          echo "Failed to pull $image after $max_attempts attempts"
          return 1
        }

        pull_with_retry ubuntu
        pull_with_retry mcr.microsoft.com/devcontainers/base:alpine
        pull_with_retry mcr.microsoft.com/devcontainers/go:1
        pull_with_retry mcr.microsoft.com/devcontainers/python:latest

    # NOTE: engineerd/setup-kind does not work on Windows runners
    - name: setup kind
      if: inputs.needs-kind == 'true' && runner.os != 'Windows'
      uses: engineerd/setup-kind@v0.6.2
      with:
        version: "v0.24.0"
        image: kindest/node:v1.34.0@sha256:7416a61b42b1662ca6ca89f02028ac133a309a2a30ba309614e8ec94d976dc5a
        name: ${{ inputs.label }}

    - name: run test (Linux)
      if: runner.os != 'Windows'
      shell: bash
      working-directory: ./e2e
      env:
        # NOTE: Github credentials are required for tests using private repos
        GH_USERNAME: ${{ inputs.gh-username }}
        GH_ACCESS_TOKEN: ${{ inputs.gh-access-token }}
      run: |
        sudo \
          GH_USERNAME="${GH_USERNAME}" \
          GH_ACCESS_TOKEN="${GH_ACCESS_TOKEN}" \
          KUBECONFIG="${KUBECONFIG:-$HOME/.kube/config}" \
          PATH="${PATH}" \
          GOROOT="${GOROOT}" \
          go test -v -ginkgo.v -timeout 3600s --ginkgo.label-filter=${{ inputs.label }}

    - name: run test (Windows)
      if: runner.os == 'Windows'
      shell: bash
      working-directory: ./e2e
      env:
        GH_USERNAME: ${{ inputs.gh-username }}
        GH_ACCESS_TOKEN: ${{ inputs.gh-access-token }}
      run: |
        GH_USERNAME="${GH_USERNAME}" \
          GH_ACCESS_TOKEN="${GH_ACCESS_TOKEN}" \
          KUBECONFIG="${KUBECONFIG:-$HOME/.kube/config}" \
          PATH="${PATH}" \
          GOROOT="${GOROOT}" \
          go test -v -ginkgo.v -timeout 3600s --ginkgo.label-filter=${{ inputs.label }}
