name: Run Integration Test
description: Run E2E integration test

inputs:
  label:
    description: Test label to filter
    required: true
  needs-kind:
    description: Whether this test needs kind
    required: false
    default: 'false'
  gh-username:
    description: GitHub username for private repo tests
    required: true
  gh-access-token:
    description: GitHub access token for private repo tests
    required: true
  binary-cache-key:
    description: Cache key for binary
    required: true
  binary-path:
    description: Path where the binary is located
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v6

    - name: Restore cached binary
      uses: actions/cache/restore@v4
      with:
        path: ${{ inputs.binary-path }}
        key: ${{ inputs.binary-cache-key }}-${{ github.sha }}
        fail-on-cache-miss: true

    - name: Make binary executable
      shell: bash
      run: chmod +x ${{ inputs.binary-path }}

    - name: Setup kind
      if: inputs.needs-kind == 'true'
      uses: engineerd/setup-kind@v0.6.2
      with:
        version: "v0.24.0"
        image: kindest/node:v1.34.0@sha256:7416a61b42b1662ca6ca89f02028ac133a309a2a30ba309614e8ec94d976dc5a
        name: ${{ inputs.label }}

    - name: Run test
      shell: bash
      working-directory: ./e2e
      env:
        GH_USERNAME: ${{ inputs.gh-username }}
        GH_ACCESS_TOKEN: ${{ inputs.gh-access-token }}
      run: |
        sudo \
          GH_USERNAME="${GH_USERNAME}" \
          GH_ACCESS_TOKEN="${GH_ACCESS_TOKEN}" \
          KUBECONFIG="${KUBECONFIG:-$HOME/.kube/config}" \
          PATH="${PATH}" \
          GOROOT="${GOROOT}" \
          go test -v -ginkgo.v -timeout 3600s --ginkgo.label-filter=${{ inputs.label }}
