name: Run Integration Test
description: Run E2E integration test

inputs:
  label:
    description: Test label to filter
    required: true
  needs-kind:
    description: Whether this test needs kind
    required: false
    default: 'false'
  gh-username:
    description: GitHub username for private repo tests
    required: true
  gh-access-token:
    description: GitHub access token for private repo tests
    required: true
  binary-cache-key:
    description: Cache key for binary
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v6

    # NOTE: Restores cache from the previous job
    - name: Setup Go
      uses: magnetikonline/action-golang-cache@v5
      with:
        go-version-file: go.mod
        cache-key-suffix: "e2e-tests"

    - name: Restore binary
      uses: actions/cache/restore@v4
      with:
        path: ./e2e/bin
        key: ${{ inputs.binary-cache-key }}

    - name: Make binary executable
      shell: bash
      run: chmod +x ./e2e/bin/devpod-linux-amd64

    - name: Setup kind
      if: inputs.needs-kind == 'true'
      uses: engineerd/setup-kind@v0.6.2
      with:
        version: "v0.24.0"
        image: kindest/node:v1.34.0@sha256:7416a61b42b1662ca6ca89f02028ac133a309a2a30ba309614e8ec94d976dc5a
        name: ${{ inputs.label }}

    - name: Setup SSH server
      shell: bash
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y openssh-server
        sudo systemctl restart ssh
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa -q || true
        cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
        chmod 600 ~/.ssh/authorized_keys
        
        # Setup SSH for root
        sudo mkdir -p /root/.ssh
        sudo chmod 700 /root/.ssh
        sudo cp ~/.ssh/id_rsa /root/.ssh/id_rsa
        sudo cp ~/.ssh/id_rsa.pub /root/.ssh/id_rsa.pub
        sudo cp ~/.ssh/authorized_keys /root/.ssh/authorized_keys
        sudo chmod 600 /root/.ssh/id_rsa /root/.ssh/authorized_keys
        sudo ssh -o StrictHostKeyChecking=no localhost echo "SSH works as root"

    - name: Run test
      shell: bash
      working-directory: ./e2e
      env:
        GH_USERNAME: ${{ inputs.gh-username }}
        GH_ACCESS_TOKEN: ${{ inputs.gh-access-token }}
        KUBECONFIG: ${{ env.KUBECONFIG }}
        GOMODCACHE: /home/runner/go/pkg/mod
        GOCACHE: /home/runner/.cache/go-build
      run: sudo -E go test -v -ginkgo.v -timeout 3600s --ginkgo.label-filter=${{ inputs.label }}
