name: Run Integration Test
description: Run E2E integration test

inputs:
  label:
    description: Test label to filter
    required: true
  needs-kind:
    description: Whether this test needs kind
    required: false
    default: 'false'
  gh-username:
    description: GitHub username for private repo tests
    required: true
  gh-access-token:
    description: GitHub access token for private repo tests
    required: true
  binary-cache-key:
    description: Cache key for binary
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v6

    # NOTE: Restores cache from the previous job
    - name: Setup Go
      uses: magnetikonline/action-golang-cache@v5
      with:
        go-version-file: go.mod
        cache-key-suffix: "e2e-tests"

    - name: Restore binary
      uses: actions/cache/restore@v4
      with:
        path: ./e2e/bin
        key: ${{ inputs.binary-cache-key }}

    - name: Make binary executable
      shell: bash
      run: chmod +x ./e2e/bin/devpod-linux-amd64

    - name: Setup kind
      if: inputs.needs-kind == 'true'
      uses: engineerd/setup-kind@v0.6.2
      with:
        version: "v0.24.0"
        image: kindest/node:v1.34.0@sha256:7416a61b42b1662ca6ca89f02028ac133a309a2a30ba309614e8ec94d976dc5a
        name: ${{ inputs.label }}

    # - name: Setup SSH directory
    #   shell: bash
    #   run: mkdir -p ~/.ssh && chmod 700 ~/.ssh

    # - name: Setup SSH server
    #   shell: bash
    #   run: |
    #     echo "=== Installing SSH server ==="
    #     sudo apt-get update -qq
    #     sudo apt-get install -y openssh-server

    #     echo "=== Starting SSH service ==="
    #     sudo systemctl restart ssh
    #     sudo systemctl status ssh

    #     echo "=== Generating SSH keys ==="
    #     ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa -q || true
    #     cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
    #     chmod 600 ~/.ssh/authorized_keys

    #     echo "=== Adding user to docker group ==="
    #     sudo usermod -aG docker $USER
    #     groups

    #     echo "=== Testing SSH connection ==="
    #     ssh -o StrictHostKeyChecking=no -o BatchMode=yes localhost echo "SSH works"

    #     echo "=== Testing Docker over SSH ==="
    #     ssh -o StrictHostKeyChecking=no -o BatchMode=yes localhost docker ps || echo "Docker not accessible over SSH"

    #     echo "=== Checking Docker socket permissions ==="
    #     ls -la /var/run/docker.sock

    #     echo "=== Testing Docker locally ==="
    #     docker ps

    - name: Run test
      shell: bash
      working-directory: ./e2e
      env:
        GH_USERNAME: ${{ inputs.gh-username }}
        GH_ACCESS_TOKEN: ${{ inputs.gh-access-token }}
        KUBECONFIG: ${{ env.KUBECONFIG }}
      run: sudo -E go test -v -ginkgo.v -timeout 3600s --ginkgo.label-filter=${{ inputs.label }}
