#!/bin/sh

# If we're outside the flatpak, we will run the flatpak command
if [ -z "${FLATPAK_ID}" ]; then
    flatpak run --command=devpod sh.loft.devpod "$@"
    result="$?"

    # In case of error check if the flatpak has been uninstalled, and prompt to
    # clean up this leftover
    if [ "${result}" -gt 0 ]; then # I: Check exit code directly with e.g. 'if ! mycmd;', not indirectly with $?.
        if ! flatpak list --app | grep -q sh.loft.devpod; then
            echo "Devpod flatpak is not installed anymore"
            script_path="$0"
            case "$script_path" in
                */*) ;;
                *) script_path="$(command -v "$script_path" 2>/dev/null || true)" ;;
            esac
            [ -n "$script_path" ] && rm -i -- "$script_path"
        fi
    fi

    exit "${result}"
fi

# copy over the binary file if absent
if [ ! -e "${XDG_DATA_HOME}/devpod" ]; then
    /usr/bin/cp /app/bin/devpod-bin "${XDG_DATA_HOME}/devpod"
else
    # or if it differs IE after an update
    if ! /usr/bin/cmp --silent /app/bin/devpod-bin "${XDG_DATA_HOME}/devpod"; then
        /usr/bin/rm -f "${XDG_DATA_HOME}/devpod"
        /usr/bin/cp /app/bin/devpod-bin "${XDG_DATA_HOME}/devpod"
    fi
fi
# We need to have it into this path so that the host is able to open it with flatpak-spawn
#
/usr/bin/flatpak-spawn --host "${XDG_DATA_HOME}/devpod" "$@"
