version: 2
project_name: devpod
release:
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: "{{ .ProjectName }}"
builds:
  - id: devpod
    hooks:
      pre:
        - sh -c 'CGO_ENABLED=1 go test $(go list ./... | grep -v -e /test -e /e2e) -race -coverprofile=dist/profile.out -covermode=atomic'
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    binary: devpod-{{ .Os }}-{{ .Arch }}
    overrides:
      - goos: linux
        goarch: amd64
        ldflags: -s -w -extldflags '-static' -X main.build={{ .Env.DEVPOD_CLI_VERSION }} -X main.commit={{ .Commit }} -X main.date={{ .Date }} -X github.com/skevetter/devpod/pkg/version.version={{ .Env.DEVPOD_CLI_VERSION }}
        tags:
          - netgo
          - osusergo
      - goos: linux
        goarch: arm64
        ldflags: -s -w -extldflags '-static' -X main.build={{ .Env.DEVPOD_CLI_VERSION }} -X main.commit={{ .Commit }} -X main.date={{ .Date }} -X github.com/skevetter/devpod/pkg/version.version={{ .Env.DEVPOD_CLI_VERSION }}
        tags:
          - netgo
          - osusergo
    ldflags: -s -w -X main.build={{ .Env.DEVPOD_CLI_VERSION }} -X main.commit={{ .Commit }} -X main.date={{ .Date }} -X github.com/skevetter/devpod/pkg/version.version={{ .Env.DEVPOD_CLI_VERSION }}
    env:
      - CGO_ENABLED=0

  - id: devpod-linux
    hooks:
      pre:
        - sh -c 'CGO_ENABLED=1 go test $(go list ./... | grep -v -e /test -e /e2e) -race -coverprofile=dist/profile.out -covermode=atomic'
    goos: [linux]
    goarch: [amd64, arm64]
    binary: devpod-{{ .Os }}-{{ .Arch }}
    ldflags: -s -w -extldflags '-static' -X main.build={{ .Env.DEVPOD_CLI_VERSION }} -X main.commit={{ .Commit }} -X main.date={{ .Date }} -X github.com/skevetter/devpod/pkg/version.version={{ .Env.DEVPOD_CLI_VERSION }}
    env:
      - CGO_ENABLED=0
    tags:
      - netgo
      - osusergo

  - id: devpod-darwin
    hooks:
      pre:
        - sh -c 'go test $(go list ./... | grep -v -e /test -e /e2e) -race -coverprofile=dist/profile.out -covermode=atomic'
    goos: [darwin]
    goarch: [amd64, arm64]
    binary: devpod-{{ .Os }}-{{ .Arch }}
    ldflags: -s -w -X main.build={{ .Env.DEVPOD_CLI_VERSION }} -X main.commit={{ .Commit }} -X main.date={{ .Date }} -X github.com/skevetter/devpod/pkg/version.version={{ .Env.DEVPOD_CLI_VERSION }}
    env:
      - CGO_ENABLED=0

  - id: devpod-windows
    goos: [windows]
    goarch: [amd64, arm64]
    binary: devpod-{{ .Os }}-{{ .Arch }}
    ldflags: -s -w -X main.build={{ .Env.DEVPOD_CLI_VERSION }} -X main.commit={{ .Commit }} -X main.date={{ .Date }} -X github.com/skevetter/devpod/pkg/version.version={{ .Env.DEVPOD_CLI_VERSION }}
    env:
      - CGO_ENABLED=0

  - id: devpod-dev
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    binary: devpod-{{ .Os }}-{{ .Arch }}
    ldflags: -s -w -extldflags '-static' -X main.build={{ .Env.DEVPOD_CLI_VERSION }} -X main.commit={{ .Commit }} -X main.date={{ .Date }} -X github.com/skevetter/devpod/pkg/version.version={{ .Env.DEVPOD_CLI_VERSION }}
    env:
      - CGO_ENABLED=0
    tags:
      - netgo
      - osusergo

  - id: devpod-pro-dev
    goos: [linux]
    goarch: [amd64]
    binary: devpod-{{ .Os }}-{{ .Arch }}-pro
    ldflags: -s -w -extldflags '-static' -X main.build={{ .Env.DEVPOD_CLI_VERSION }} -X main.commit={{ .Commit }} -X main.date={{ .Date }} -X github.com/skevetter/devpod/pkg/version.version={{ .Env.DEVPOD_CLI_VERSION }}
    env:
      - CGO_ENABLED=0
    tags:
      - profile
      - osusergo
      - netgo
    hooks:
      post:
        - cmd: kubectl -n "{{ .Env.DEVPOD_PRO_NS | default "default" }}" cp --no-preserve=true dist/devpod-pro_linux_amd64_v1/devpod-{{ .Os }}-{{ .Arch }}-pro "$(kubectl -n "{{ .Env.DEVPOD_PRO_NS | default "default" }}" get pods -l app=loft -o jsonpath="{.items[0].metadata.name}")":/usr/local/bin/devpod
          env:
            - DEVPOD_PRO_NS={{ .Env.DEVPOD_PRO_NS | default "default" }}

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
checksum:
  name_template: checksums.txt
report_sizes: true
