version: "3"

tasks:
  cli:tidy:
    desc: tidy go.mod and go.sum
    cmd: go mod tidy

  cli:lint:
    desc: run devpod linters
    cmd: golangci-lint run

  cli:build:
    desc: build devpod CLI
    env:
      GITHUB_REPOSITORY_OWNER: skevetter
    cmd: goreleaser build --id devpod --snapshot --clean

  cli:build:dev:
    desc: build devpod CLI for development
    env:
      GITHUB_REPOSITORY_OWNER: skevetter
    cmd: goreleaser build --id devpod-dev --snapshot --clean

  cli:build:setup-cache:
    desc: setup cache for CLI builds
    deps:
      - cli:build:dev
    cmds:
      - task: cli:build:teardown-cache
      - mkdir -p "${TMPDIR:-/tmp/}devpod-cache"
      - cp dist/devpod-dev_linux_amd64_v1/devpod-linux-amd64 "${TMPDIR:-/tmp/}devpod-cache/devpod-linux-amd64"

  cli:build:teardown-cache:
    desc: teardown cache for CLI builds
    cmds:
      - rm -rf "${TMPDIR:-/tmp/}devpod-cache"

  cli:test:
    desc: run devpod unit tests
    cmd: go test $(go list ./... | grep -v -e /test -e /e2e) -race -coverprofile=dist/profile.out -covermode=atomic

  cli:test:e2e:build:
    desc: build devpod for e2e tests
    status:
      - test -f e2e/bin/devpod-linux-amd64
    cmds:
      - task: cli:build:dev
      - mkdir -p e2e/bin
      - cp dist/devpod-dev_linux_amd64_v1/devpod-linux-amd64 e2e/bin/devpod-linux-amd64

  cli:test:e2e:
    desc: run e2e tests
    deps:
      - cli:test:e2e:build
      - cli:test:e2e:ginkgo:install
    dir: e2e
    cmd: go run github.com/onsi/ginkgo/v2/ginkgo@latest

  cli:test:e2e:suite:
    # usage: task cli:test:e2e:suite -- "test suite name"
    desc: run e2e tests suite
    deps:
      - cli:test:e2e:ginkgo:install
    dir: e2e
    cmd: go run github.com/onsi/ginkgo/v2/ginkgo@latest --label-filter "{{ .CLI_ARGS }}"

  cli:test:e2e:focus:
    # usage: task cli:test:e2e:focus -- "test suite pattern"
    desc: run focused e2e tests
    deps:
      - cli:test:e2e:ginkgo:install
    dir: e2e
    cmd: go run github.com/onsi/ginkgo/v2/ginkgo@latest --focus "{{ .CLI_ARGS }}"

  cli:test:e2e:kind:setup:
    desc: setup kind cluster for e2e tests
    cmd: kind create cluster --image kindest/node:v1.34.0@sha256:7416a61b42b1662ca6ca89f02028ac133a309a2a30ba309614e8ec94d976dc5a

  cli:test:e2e:kind:teardown:
    desc: teardown kind cluster for e2e tests
    cmd: kind delete cluster

  cli:test:e2e:ginkgo:install:
    desc: install ginkgo for e2e tests
    env:
      GOPROXY: direct
    status: [command -v ginkgo >/dev/null 2>&1]
    cmd: go install github.com/onsi/ginkgo/v2/ginkgo@latest

  desktop:build:
    desc: build devpod Desktop application
    dir: desktop
    cmds:
      - cmd: yarn install --frozen-lockfile
      - cmd: yarn lint:ci
      - cmd: yarn format:check
      - cmd: yarn types:check
      - cmd: yarn build

  desktop:update-deps:
    desc: update yarn dependencies
    dir: desktop
    cmd: yarn upgrade --latest

  desktop:tauri:setup:
    desc: setup tauri desktop application
    dir: desktop
    cmds:
      - task: cli:build:dev
      - cmd: cp ../dist/devpod-dev_linux_amd64_v1/devpod-linux-amd64 ./src-tauri/bin/devpod-cli-x86_64-unknown-linux-gnu
      - cmd: yarn install --frozen-lockfile

  desktop:tauri:generate-types:
    desc: generate desktop types
    dir: desktop/src-tauri
    cmds:
      - rm -rf ../src/gen && mkdir -p ../dist
      - touch ../dist/index.html
      - cargo test
      - mkdir -p ../src/gen
      - cp -r bindings/* ../src/gen/
      - rm -rf bindings
      - |
        touch ../src/gen/index.ts
        for f in ../src/gen/*.ts; do
          echo "export * from './$(basename "$f" .ts)'" >> ../src/gen/index.ts
        done
      - cd ../ && yarn prettier --write src/gen

  desktop:tauri:generate-signing-keys:
    desc: Generate Tauri signing keys
    dir: desktop
    cmd: yarn tauri signer generate --ci -w ../app.key

  desktop:tauri:dev:
    desc: run tauri application in dev mode
    dir: desktop
    cmd: yarn desktop:dev

  desktop:tauri:build-app:
    desc: build tauri application
    dir: desktop
    cmd: yarn desktop:build:dev

  desktop:tauri:update-deps:
    desc: update tauri dependencies
    dir: desktop/src-tauri
    cmd: cargo update

  github:dev-release:upload:
    desc: upload dev binaries to GitHub release tag v0.0.0-10 for testing
    cmds:
      - cmd: |
          TMP_DIR="$(mktemp -d)"
          cp dist/devpod-dev_linux_amd64_v1/devpod-linux-amd64 "$TMP_DIR/devpod-linux-amd64"
          gh release upload v0.0.0-10 dist/devpod-dev_linux_amd64_v1/devpod-linux-amd64 --repo skevetter/devpod --clobber
          rm -rf "$TMP_DIR"
