name: Create macOS Release Artifacts
description: Build macOS desktop app with Tauri

inputs:
  target:
    description: Build target architecture
    required: true
  release_id:
    description: GitHub release ID
    required: true
  github_token:
    description: GitHub token for uploading assets
    required: true
  tauri_private_key:
    description: Tauri private key for signing
    required: false
  tauri_key_password:
    description: Tauri key password
    required: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@v6

    - name: Build Desktop App
      uses: tauri-apps/tauri-action@v0.6
      with:
        releaseId: ${{ inputs.release_id }}
        projectPath: "./desktop"
        args: "--target ${{ inputs.target }}"
        includeUpdaterJson: true
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        TAURI_PRIVATE_KEY: ${{ inputs.tauri_private_key }}
        TAURI_SIGNING_PRIVATE_KEY: ${{ inputs.tauri_private_key }}
        TAURI_KEY_PASSWORD: ${{ inputs.tauri_key_password }}
        TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ inputs.tauri_key_password }}
        CI: false
