name: Compile Binary
description: Compile binary

inputs:
  cache-key-suffix:
    description: Suffix for cache key
    required: true

runs:
  using: composite
  steps:
    - name: Setup Go
      uses: magnetikonline/action-golang-cache@v5
      with:
        go-version-file: go.mod
        cache-key-suffix: ${{ inputs.cache-key-suffix }}

    - name: Compile
      shell: bash
      run: |
        go generate ./...
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build main.go
