name: Create Release
description: Get version and release information for DevPod release workflow

outputs:
  package_version:
    description: Processed package version
    value: ${{ steps.get-version.outputs.package_version }}
  original_package_version:
    description: Original package version from tag
    value: ${{ steps.get-version.outputs.original_package_version }}
  release_id:
    description: GitHub release ID
    value: ${{ steps.get-release.outputs.id }}

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v6
      with:
        node-version: "latest"

    - run: npm install semver
      shell: bash

    - name: get version
      uses: actions/github-script@v6
      id: get-version
      with:
        script: |
          const semver = require("semver")
          const refName = `${process.env.GITHUB_REF_NAME}`
          let version = refName.split("v")[1]

          core.info(`Original Version: ${version}`)
          core.setOutput("original_package_version", version)

          const parsed = semver.parse(version);
          const supportedPreleases = [
            { tag: "alpha", number: 1 },
            { tag: "beta", number: 2 },
            { tag: "rc", number: 3 },
          ];
          const maybePrelease = semver.prerelease(version);
          const maybeSupported = supportedPreleases.find(
            (p) => p.tag === maybePrelease?.[0]
          );

          // If we have a prelease and it is in the supported range, then we can use it
          if (maybePrelease && maybeSupported) {
            version = `${parsed.major}.${parsed.minor}.${parsed.patch}-${
              maybeSupported.number
            }${maybePrelease[1] ?? 0}`;
          }

          if(maybePrelease && !maybeSupported) {
            core.setFailed(`Unsupported prerelease: ${version}`)
          }

          core.info(`Version: ${version}`)
          core.setOutput("package_version", version)

    - name: get release
      uses: actions/github-script@v6
      id: get-release
      with:
        script: |
          // Find the prerelease release in our repo that triggered this workflow
          const refName = `${process.env.GITHUB_REF_NAME}`

          const res = await github.rest.repos.listReleases({
            owner: context.repo.owner,
            repo: context.repo.repo,
            per_page: 10,
          })
          const release = res.data.find((r) => r.tag_name === refName && r.prerelease)
          if(!release) { core.setFailed("Unable to find prerelease for this workflow") }

          core.setOutput("id", release.id)
