name: Build CLI
description: Build DevPod CLI sidecar binary

inputs:
  host:
    description: Host OS (ubuntu-22.04, macos-latest, windows-latest)
    required: true
  target:
    description: Build target architecture
    required: true
  os:
    description: Target OS (linux, darwin, windows)
    required: true
  arch:
    description: Target architecture (amd64, arm64)
    required: true
  version:
    description: Version to embed in binary
    required: true
  telemetry_private_key:
    description: Telemetry private key
    required: false
  crane_private_key:
    description: Crane signing key
    required: false

runs:
  using: composite
  steps:
    - name: Build Sidecar CLI (Unix)
      if: inputs.host != 'windows-latest'
      shell: bash
      run: |
        BIN_NAME=devpod-cli-${{ inputs.target }}
        GOOS=${{ inputs.os }} GOARCH=${{ inputs.arch }} CGO_ENABLED=0 go build -ldflags "-s -w -X github.com/skevetter/devpod/pkg/version.version="v${{ inputs.version }}" -X github.com/skevetter/devpod/pkg/telemetry.telemetryPrivateKey=${{ inputs.telemetry_private_key }} -X github.com/skevetter/devpod/pkg/devcontainer/crane.craneSigningKey="${{ inputs.crane_private_key }}"" -o "test/$BIN_NAME"
        cp "test/$BIN_NAME" "desktop/src-tauri/bin/$BIN_NAME"
        ls desktop/src-tauri/bin

    - name: Build Sidecar CLI (Windows)
      if: inputs.host == 'windows-latest'
      shell: cmd
      run: |
        set GOOS=windows
        set GOARCH=${{ inputs.arch }}
        set BIN_NAME=devpod-cli-${{ inputs.target }}.exe

        go build -ldflags "-s -w -X github.com/skevetter/devpod/pkg/version.version="v${{ inputs.version }}" -X github.com/skevetter/devpod/pkg/telemetry.telemetryPrivateKey=${{ inputs.telemetry_private_key }}" -o "test\%BIN_NAME%"

        xcopy /F /Y "test\%BIN_NAME%" desktop\src-tauri\bin\*
