name: Build CLI
description: Build DevPod CLI sidecar binary

inputs:
  host:
    description: Host OS (ubuntu-22.04, macos-latest, windows-latest)
    required: true
  target:
    description: Build target architecture
    required: true
  os:
    description: Target OS (linux, darwin, windows)
    required: true
  arch:
    description: Target architecture (amd64, arm64)
    required: true
  version:
    description: Version to embed in binary
    required: true
  telemetry_private_key:
    description: Telemetry private key
    required: false
  crane_private_key:
    description: Crane signing key
    required: false
  output_path:
    description: Output path for the CLI binary
    required: true
  sidecar_path:
    description: Output path for the sidecar binary (for desktop)
    required: true

runs:
  using: composite
  steps:
    - name: build sidecar CLI (Linux/macOS)
      if: inputs.host != 'windows-latest'
      shell: bash
      run: |
        BIN_NAME=devpod-cli-${{ inputs.target }}
        mkdir -p ${{ inputs.output_path }}
        mkdir -p ${{ inputs.sidecar_path }}
        GOOS=${{ inputs.os }} GOARCH=${{ inputs.arch }} CGO_ENABLED=0 go build -ldflags "-s -w -X github.com/skevetter/devpod/pkg/version.version="v${{ inputs.version }}" -X github.com/skevetter/devpod/pkg/telemetry.telemetryPrivateKey=${{ inputs.telemetry_private_key }} -X github.com/skevetter/devpod/pkg/devcontainer/crane.craneSigningKey="${{ inputs.crane_private_key }}"" -o "${{ inputs.output_path }}/$BIN_NAME"
        cp "${{ inputs.output_path }}/$BIN_NAME" "${{ inputs.sidecar_path }}/$BIN_NAME"
        ls ${{ inputs.sidecar_path }}

    - name: build sidecar CLI (Windows)
      if: inputs.host == 'windows-latest'
      shell: cmd
      run: |
        set GOOS=windows
        set GOARCH=${{ inputs.arch }}
        set BIN_NAME=devpod-cli-${{ inputs.target }}.exe

        if not exist "${{ inputs.output_path }}" mkdir "${{ inputs.output_path }}"
        if not exist "${{ inputs.sidecar_path }}" mkdir "${{ inputs.sidecar_path }}"

        go build -ldflags "-s -w -X github.com/skevetter/devpod/pkg/version.version="v${{ inputs.version }}" -X github.com/skevetter/devpod/pkg/telemetry.telemetryPrivateKey=${{ inputs.telemetry_private_key }}" -o "${{ inputs.output_path }}\%BIN_NAME%"

        xcopy /F /Y "${{ inputs.output_path }}\%BIN_NAME%" "${{ inputs.sidecar_path }}\*"
