name: Create Windows Release Artifacts
description: Build Windows desktop app and upload release assets

inputs:
  target:
    description: Build target architecture
    required: true
  arch:
    description: Architecture (amd64, arm64)
    required: true
  package_version:
    description: Package version
    required: true
  release_id:
    description: GitHub release ID
    required: true
  github_token:
    description: GitHub token for uploading assets
    required: true
  tauri_private_key:
    description: Tauri private key for signing
    required: false
  tauri_key_password:
    description: Tauri key password
    required: false

runs:
  using: composite
  steps:
    - name: build tauri app
      uses: tauri-apps/tauri-action@v0.6
      with:
        projectPath: "./desktop"
        args: "--target ${{ inputs.target }}"
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        TAURI_SIGNING_PRIVATE_KEY: ${{ inputs.tauri_private_key }}
        TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ inputs.tauri_key_password }}

    - name: Create MSI zip file
      shell: powershell
      run: |
        $bundlePath = "desktop/src-tauri/target/${{ inputs.target }}/release/bundle/msi"
        $msiFile = "DevPod_${{ inputs.package_version }}_x64_en-US.msi"

        if (Test-Path "$bundlePath/$msiFile") {
          Compress-Archive -Path "$bundlePath/$msiFile" -DestinationPath "$bundlePath/$msiFile.zip" -Force
          Write-Host "Created $bundlePath/$msiFile.zip"
        }

    - name: upload release assets
      uses: actions/github-script@v8
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        script: |
          const fs = require("fs")
          const version = "${{ inputs.package_version }}"
          const target = "${{ inputs.target }}"
          const arch = "${{ inputs.arch }}"

          const bundlePath = `desktop/src-tauri/target/${target}/release/bundle`
          const msiFile = `DevPod_${version}_x64_en-US.msi`
          const nsisFile = `DevPod_${version}_x64-setup.exe`

          const assets = [
            { name: `devpod-windows-${arch}.exe`, path: `desktop/src-tauri/bin/devpod-cli-${target}.exe` },
            { name: msiFile, path: `${bundlePath}/msi/${msiFile}` },
            { name: `${msiFile}.zip`, path: `${bundlePath}/msi/${msiFile}.zip` },
            { name: `${msiFile}.sig`, path: `${bundlePath}/msi/${msiFile}.sig` },
            { name: nsisFile, path: `${bundlePath}/nsis/${nsisFile}` }
          ]

          for (const asset of assets) {
            if (!fs.existsSync(asset.path)) {
              console.warn(`skipping missing file ${asset.path}`)
              continue
            }

            console.log(`uploading ${asset.name}`)
            await github.rest.repos.uploadReleaseAsset({
              headers: {
                "content-type": "application/octet-stream",
                "content-length": fs.statSync(asset.path).size
              },
              name: asset.name,
              data: fs.readFileSync(asset.path),
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: "${{ inputs.release_id }}"
            })
          }
