name: Create Windows Release Artifacts
description: Build Windows desktop app and upload release assets

inputs:
  target:
    description: Build target architecture
    required: true
  arch:
    description: Architecture (amd64, arm64)
    required: true
  package_version:
    description: Package version
    required: true
  release_id:
    description: GitHub release ID
    required: true
  github_token:
    description: GitHub token for uploading assets
    required: true
  tauri_private_key:
    description: Tauri private key for signing
    required: false
  tauri_key_password:
    description: Tauri key password
    required: false

runs:
  using: composite
  steps:
    - name: build tauri app
      uses: tauri-apps/tauri-action@v0.6
      with:
        projectPath: "./desktop"
        args: "--target ${{ inputs.target }}"
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        TAURI_SIGNING_PRIVATE_KEY: ${{ inputs.tauri_private_key }}
        TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ inputs.tauri_key_password }}

    - uses: actions/github-script@v8
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        script: |
          const fs = require("fs")

          const version = "${{ inputs.package_version }}"

          // prepare MSI vars
          const msiName = `DevPod_${version}_x64_en-US.msi`
          const msiPath = `desktop/src-tauri/target/${{ inputs.target }}/release/bundle/msi/${msiName}`
          const msiZipName = `${msiName}.zip`
          const msiZipPath = `desktop/src-tauri/target/${{ inputs.target }}/release/bundle/msi/${msiZipName}`
          const msiZipSigName = `${msiName}.zip.sig`
          const msiZipSigPath = `desktop/src-tauri/target/${{ inputs.target }}/release/bundle/msi/${msiZipSigName}`

          // prepare NSIS vars
          // the installer itself is suffixed with `.exe` but updater artifacts end with `.nsis.*`
          const nsisName = `DevPod_${version}_x64-setup`
          const nsisPath = `desktop/src-tauri/target/${{ inputs.target }}/release/bundle/nsis/${nsisName}.exe`

          // Let's skip uploading the updater artifacts until we've figured out auto updating for both nsis and msi
          // const nsisZipName = `${nsisName}.nsis.zip`
          // const nsisZipPath = `desktop/src-tauri/target/${{ inputs.target }}/release/bundle/nsis/${nsisZipName}`
          // const nsisZipSigName = `${nsisName}.nsis.zip.sig`
          // const nsisZipSigPath = `desktop/src-tauri/target/${{ inputs.target }}/release/bundle/nsis/${nsisZipSigName}`

          const cliName = "devpod-windows-${{ inputs.arch }}.exe"
          const cliPath = "desktop/src-tauri/bin/devpod-cli-${{ inputs.target }}.exe"

          const releaseId = "${{ inputs.release_id }}"

          const releaseAssets = [
            { name: cliName, path: cliPath },

            { name: msiName, path: msiPath },
            { name: msiZipName, path: msiZipPath },
            { name: msiZipSigName, path: msiZipSigPath },

            { name: `${nsisName}.exe`, path: nsisPath },
            // { name: nsisZipName, path: nsisZipPath },
            // { name: nsisZipSigName, path: nsisZipSigPath },
          ]
          for (const asset of releaseAssets) {
            console.log("Attempting to upload release asset: ", asset)
            await github.rest.repos.uploadReleaseAsset({
              headers: {
                "content-type": "application/zip",
                "content-length": fs.statSync(asset.path).size
              },
              name: asset.name,
              data: fs.readFileSync(asset.path),
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: releaseId
            })
          }
