name: Create Linux Release Artifacts
description: Build and upload Linux-specific release artifacts (tar.gz, flatpak assets)

inputs:
  target:
    description: Build target architecture
    required: true
  package_version:
    description: Package version
    required: true
  release_id:
    description: GitHub release ID
    required: true
  github_token:
    description: GitHub token for uploading assets
    required: true
  tauri_private_key:
    description: Tauri private key for signing
    required: false
  tauri_key_password:
    description: Tauri key password
    required: false
  app_image_sign:
    description: AppImage signing flag
    required: false
  app_image_sign_key:
    description: AppImage signing key
    required: false
  app_image_sign_passphrase:
    description: AppImage signing passphrase
    required: false

runs:
  using: composite
  steps:
    - name: build tauri app
      uses: tauri-apps/tauri-action@v0.6
      with:
        releaseId: ${{ inputs.release_id }}
        projectPath: "./desktop"
        args: "--target ${{ inputs.target }} --config src-tauri/tauri-flatpak.conf.json --bundles appimage,deb,updater"
        includeUpdaterJson: true
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        TAURI_SIGNING_PRIVATE_KEY: ${{ inputs.tauri_private_key }}
        TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ inputs.tauri_key_password }}
        SIGN: ${{ inputs.app_image_sign }}
        SIGN_KEY: ${{ inputs.app_image_sign_key }}
        APPIMAGETOOL_SIGN_PASSPHRASE: ${{ inputs.app_image_sign_passphrase }}

    - name: build linux tar.gz
      shell: bash
      run: |
        cd ./desktop/src-tauri/target/${{ inputs.target }}/release/bundle/appimage/DevPod.AppDir || exit 1
        tar --exclude=usr/bin/xdg-open --exclude=usr/lib --exclude=usr/share/doc --exclude=usr/share/glib-2.0 -zcvf DevPod-desktop.tar.gz usr
        mv DevPod-desktop.tar.gz ../../DevPod-${{ inputs.package_version }}.tar.gz

    - name: upload linux tar.gz asset
      uses: actions/github-script@v8
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        script: |
          const fs = require("fs")

          const releaseId = "${{ inputs.release_id }}"
          const assetName = "DevPod-${{ inputs.package_version }}.tar.gz"
          const assetPath = `desktop/src-tauri/target/${{ inputs.target }}/release/bundle/${assetName}`

          console.log("Attempting to upload release asset: ", assetName)

          await github.rest.repos.uploadReleaseAsset({
            headers: {
              "content-type": "application/zip",
              "content-length": fs.statSync(assetPath).size
            },
            name: assetName,
            data: fs.readFileSync(assetPath),
            owner: context.repo.owner,
            repo: context.repo.repo,
            release_id: releaseId
          })

    - name: upload appimage asset
      uses: actions/github-script@v8
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        script: |
          const fs = require("fs")

          const releaseId = "${{ inputs.release_id }}"
          const assetName = "DevPod.desktop"
          const assetPath = `desktop/src-tauri/target/${{ inputs.target }}/release/bundle/deb/DevPod_${{ inputs.package_version }}_amd64/data/usr/share/applications/${assetName}`

          console.log("Attempting to upload release asset: ", assetName)

          await github.rest.repos.uploadReleaseAsset({
            headers: {
              "content-type": "application/zip",
              "content-length": fs.statSync(assetPath).size
            },
            name: assetName,
            data: fs.readFileSync(assetPath),
            owner: context.repo.owner,
            repo: context.repo.repo,
            release_id: releaseId
          })

          const mdAssetName = "DevPod.metainfo.xml"
          const mdAssetPath = `desktop/flatpak/${mdAssetName}`

          console.log("Attempting to upload release asset: ", mdAssetName)

          await github.rest.repos.uploadReleaseAsset({
            headers: {
              "content-type": "application/zip",
              "content-length": fs.statSync(mdAssetPath).size
            },
            name: mdAssetName,
            data: fs.readFileSync(mdAssetPath),
            owner: context.repo.owner,
            repo: context.repo.repo,
            release_id: releaseId
          })

    - name: generate flatpak manifest
      shell: bash
      run: |
        export VERSION="${{ inputs.package_version }}"
        export debPath="desktop/src-tauri/target/${{ inputs.target }}/release/bundle/deb/DevPod_${{ inputs.package_version }}_amd64.deb"
        export desktopPath="desktop/src-tauri/target/${{ inputs.target }}/release/bundle/deb/DevPod_${{ inputs.package_version }}_amd64/data/usr/share/applications/${assetName}/DevPod.desktop"
        export metaPath="desktop/flatpak/DevPod.metainfo.xml"
        export SHA256=$(sha256sum "${debPath}" | cut -f1 -d ' ')
        export DESKTOP_SHA256=$(sha256sum "${desktopPath}" | cut -f1 -d ' ')
        export META_SHA256=$(sha256sum "${metaPath}" | cut -f1 -d ' ')
        envsubst < desktop/flatpak/sh.loft.devpod.tmpl > desktop/flatpak/sh.loft.devpod.yaml
