name: Upload CLI Asset
description: Upload CLI binary to GitHub release

inputs:
  target:
    description: Build target architecture
    required: true
  os:
    description: Target OS (linux, darwin)
    required: true
  arch:
    description: Target architecture (amd64, arm64)
    required: true
  release_id:
    description: GitHub release ID
    required: true
  github_token:
    description: GitHub token for uploading assets
    required: true

runs:
  using: composite
  steps:
    - uses: actions/github-script@v8
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        script: |
          const fs = require("fs")

          const releaseId = "${{ inputs.release_id }}"
          const assetName = "devpod-${{ inputs.os }}-${{ inputs.arch }}"
          const assetPath = "desktop/src-tauri/bin/devpod-cli-${{ inputs.target }}"

          console.log("Attempting to upload release asset: ", assetName)

          await github.rest.repos.uploadReleaseAsset({
            headers: {
              "content-type": "application/zip",
              "content-length": fs.statSync(assetPath).size
            },
            name: assetName,
            data: fs.readFileSync(assetPath),
            owner: context.repo.owner,
            repo: context.repo.repo,
            release_id: releaseId
          })
